[package]
name = "romanos"
version = "0.1.0"
authors = ["HenryTufano <rique_3l@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
